#!/bin/bash
# Uses speedtest cli from Oookla to test internet speed and format for nagios
# Felipe Ferreira 08/2016
# @fcoach66 04/2021
# Version 3.0

downw=$1
downc=$2
upw=$3
upc=$4

TMP=".speedtest.$SERVER.$RANDOM"

if [  -z $4 ]; then
 echo "UNOKNWN - Please pass all 4 paramateres $0 <download_warn> <download_crit> <upload_warn> <upload_crit>"
 exit 3
fi

SCRIPT="/usr/bin//speedtest"
if [ -f $SCRIPT ]; then
 CMD="$SCRIPT > $TMP  2>&1"
else
 echo "UNKONW - could not find requirements: speedtest"
 echo "Download speedtest from https://www.speedtest.net/apps/cli"
 exit 3
fi

#echo $CMD
R=$(eval $CMD)
P=$(grep Latency $TMP |awk '{ print $(NF -4) }')
D=$(grep Download $TMP |awk '{ print $(NF -5)}' |awk -F"." '{print $1}' )
U=$(grep Upload $TMP |awk '{ print $(NF -5) }'  |awk -F"." '{print $1}' )

MSG="Latency $P ms Download $D Mbit/s Upload $U Mbit/s |Download=$D;Upload=$U"
rm -f $TMP

if [ $D -lt $downc ] || [ $U -lt $upc ]; then
 echo "CRITICAL - $MSG"
 exit 2
elif [ $D -lt $downw ] || [ $U -lt $upw ]; then
 echo "WARNING - $MSG"
 exit 1
else
 echo "OK - $MSG"
 exit 0
fi
